path = r'C:/Users/7MAKSACOD PC/Desktop/Daara Al Amine Academy/SITE WEB AAA/translations.js'
with open(path, 'r', encoding='utf-8') as f:
    c = f.read()

orig_len = len(c)
replacements = [
    # ── FR ──
    ('"mixed_subtitle": "Externat — retour à la maison chaque soir"',
     '"mixed_subtitle": "Internat — Coran & académique, hébergement inclus"'),
    ('"card3_subtitle": "Externat : Coran le matin, académique l\'après-midi, retour à la maison chaque soir"',
     '"card3_subtitle": "Internat : Coran le matin, académique l\'après-midi, hébergement et repas inclus"'),
    ('"hero_title": "Programme Mixte en Externat"',
     '"hero_title": "Programme Mixte Internat"'),
    ('"hero_subtitle": "Coran le matin, cursus académique l\'après-midi. Votre enfant rentre à la maison chaque soir — pour les familles qui veulent garder leur enfant proche tout en lui offrant Tahfiz + études."',
     '"hero_subtitle": "Coran le matin, cursus académique l\'après-midi. Hébergement et repas inclus — pour les familles qui souhaitent offrir à leur enfant Tahfiz + études dans un cadre islamique complet."'),
    ('"hero_badge": "Externat"', '"hero_badge": "Internat"'),
    ('"price_label3": "Retour à la maison chaque soir"', '"price_label3": "Hébergement inclus"'),
    ('"features_intro": "La solution idéale pour les familles qui souhaitent combiner éducation coranique et académique sans internat."',
     '"features_intro": "La solution idéale pour les familles qui souhaitent offrir à leur enfant Tahfiz + académique dans un cadre internat structuré."'),
    ('"feat3_title": "Retour chaque soir"', '"feat3_title": "Hébergement inclus"'),
    ('"feat3_desc": "Votre enfant rentre chez vous chaque soir. Idéal pour les familles qui souhaitent rester proches."',
     '"feat3_desc": "Hébergement et repas inclus sur place. Votre enfant est encadré 24h/24 dans un cadre islamique bienveillant."'),
    ('"sched_row_9": "Retour à la maison"', '"sched_row_9": "Maghreb & coucher"'),
    ('"advantages_title": "Pourquoi choisir l\'externat ?"', '"advantages_title": "Pourquoi choisir le programme mixte internat ?"'),
    ('"adv1_title": "Lien familial préservé"', '"adv1_title": "Immersion totale"'),
    ('"adv1_desc": "Votre enfant rentre chaque soir. Il garde un lien quotidien fort avec sa famille."',
     '"adv1_desc": "Encadrement islamique 24h/24 : Coran, académique, repas, sport et coucher dans un cadre structuré et bienveillant."'),
    ('"adv2_desc": "Coran sérieux + académique solide, sans l\'éloignement de l\'internat."',
     '"adv2_desc": "Coran sérieux + académique solide, avec la discipline et l\'encadrement de l\'internat."'),
    ('"adv4_desc": "Moins coûteux que l\'internat car pas d\'hébergement ni de repas inclus."',
     '"adv4_desc": "Hébergement et 3 repas halal par jour inclus dans la mensualité."'),
    ('"adv6_desc": "Nos élèves en externat obtiennent d\'excellents résultats en Tahfiz et académique."',
     '"adv6_desc": "Nos élèves du programme mixte obtiennent d\'excellents résultats en Tahfiz et académique."'),
    ('"cta_title": "Inscrivez votre enfant en Programme Mixte"',
     '"cta_title": "Inscrivez votre enfant au Programme Mixte Internat"'),
    ('"timeline_event3_desc": "Lancement du Programme Mixte en externat, des cours en ligne et des cours gratuits en wolof. L\'académie grandit pour répondre à toutes les familles."',
     '"timeline_event3_desc": "Lancement du Programme Mixte internat, des cours en ligne et des cours gratuits en wolof. L\'académie grandit pour répondre à toutes les familles."'),
    # ── EN ──
    ('"mixed_subtitle": "Day school — back home every evening"',
     '"mixed_subtitle": "Boarding — Quran & academics, accommodation included"'),
    ('"card3_subtitle": "Day school: Quran in the morning, academic in the afternoon, home every evening"',
     '"card3_subtitle": "Boarding: Quran in the morning, academic in the afternoon, accommodation included"'),
    ('"hero_title": "Day Program (Externat)"', '"hero_title": "Mixed Boarding Programme"'),
    ('"hero_subtitle": "Quran in the morning, academic curriculum in the afternoon. Your child comes home every evening — for families who want to keep their child close while offering Tahfiz + studies."',
     '"hero_subtitle": "Quran in the morning, academic curriculum in the afternoon. Accommodation and meals included — for families who want to offer their child Tahfiz + studies in a complete Islamic boarding setting."'),
    ('"hero_badge": "Day School"', '"hero_badge": "Boarding"'),
    ('"price_label3": "Home every evening"', '"price_label3": "Accommodation included"'),
    ('"features_title": "Advantages of the day programme"', '"features_title": "Advantages of the mixed boarding programme"'),
    ('"features_intro": "The ideal solution for families who want to combine Quranic and academic education without boarding."',
     '"features_intro": "The ideal solution for families who want to combine Quranic and academic education in a full boarding setting."'),
    ('"feat3_title": "Home every evening"', '"feat3_title": "Accommodation included"'),
    ('"feat3_desc": "Your child returns home every evening. Ideal for families who want to stay close."',
     '"feat3_desc": "Accommodation and meals included on-site. Your child is supervised 24/7 in a caring Islamic environment."'),
    ('"sched_row_9": "Return home"', '"sched_row_9": "Maghrib & bedtime"'),
    ('"schedule_subtitle": "A typical day in the Day Programme"', '"schedule_subtitle": "A typical day in the Mixed Boarding Programme"'),
    ('"advantages_title": "Why choose the day programme?"', '"advantages_title": "Why choose the mixed boarding programme?"'),
    ('"adv1_title": "Family bond preserved"', '"adv1_title": "Full immersion"'),
    ('"adv1_desc": "Your child comes home every evening. They maintain a strong daily bond with their family."',
     '"adv1_desc": "24/7 Islamic supervision: Quran, academics, meals, sport and sleep in a structured environment."'),
    ('"adv2_desc": "Serious Quran + solid academics, without the separation of boarding."',
     '"adv2_desc": "Serious Quran + solid academics, with the discipline and rigour of a boarding school."'),
    ('"adv4_desc": "Less costly than boarding since accommodation and meals are not included."',
     '"adv4_desc": "Accommodation and 3 halal meals per day included in the monthly fee."'),
    ('"adv6_desc": "Our day students achieve excellent results in both Tahfiz and academics."',
     '"adv6_desc": "Our mixed programme students achieve excellent results in both Tahfiz and academics."'),
    ('"cta_title": "Enroll your child in the Day Programme"', '"cta_title": "Enroll your child in the Mixed Boarding Programme"'),
    ('"timeline_event3_desc": "Launch of the Mixed Day Programme, online courses and free Wolof courses. The academy grows to serve all families."',
     '"timeline_event3_desc": "Launch of the Mixed Boarding Programme, online courses and free Wolof courses. The academy grows to serve all families."'),
    # ── AR ──
    ('"mixed_subtitle": "خارجي — العودة إلى المنزل كل مساء"',
     '"mixed_subtitle": "داخلية — قرآن وأكاديمي، الإقامة مشمولة"'),
    ('"card3_subtitle": "خارجي: قرآن في الصباح، دراسة بعد الظهر، العودة إلى المنزل كل مساء"',
     '"card3_subtitle": "داخلية: قرآن في الصباح، دراسة بعد الظهر، الإقامة مشمولة"'),
    ('"hero_title": "البرنامج المختلط — خارجي"', '"hero_title": "البرنامج المختلط الداخلي"'),
    ('"hero_subtitle": "قرآن في الصباح، منهج أكاديمي بعد الظهر. يعود طفلك إلى المنزل كل مساء — للأسر التي تريد إبقاء أطفالها قريبين مع تقديم التحفيظ والدراسة."',
     '"hero_subtitle": "قرآن في الصباح، منهج أكاديمي بعد الظهر. الإقامة والوجبات مشمولة — للأسر التي تريد تقديم التحفيظ والدراسة في بيئة إسلامية متكاملة."'),
    ('"hero_badge": "خارجي"', '"hero_badge": "داخلية"'),
    ('"price_label3": "العودة إلى المنزل كل مساء"', '"price_label3": "الإقامة مشمولة"'),
    ('"features_intro": "الحلّ المثالي للأسر التي تريد الجمع بين التربية القرآنية والأكاديمية دون داخلية."',
     '"features_intro": "الحلّ المثالي للأسر التي تريد الجمع بين التربية القرآنية والأكاديمية في نظام داخلي متكامل."'),
    ('"feat3_title": "عودة كل مساء"', '"feat3_title": "إقامة مشمولة"'),
    ('"feat3_desc": "يعود طفلك إلى المنزل كل مساء. مثالي للأسر التي تريد البقاء قريبة."',
     '"feat3_desc": "إقامة ووجبات مشمولة. طفلك تحت إشراف 24 ساعة في بيئة إسلامية منظَّمة وحانية."'),
    ('"sched_row_9": "العودة إلى المنزل"', '"sched_row_9": "المغرب والنوم"'),
    ('"advantages_title": "لماذا تختار الخارجي؟"', '"advantages_title": "لماذا تختار البرنامج المختلط الداخلي؟"'),
    ('"adv1_title": "الرابط الأسري محفوظ"', '"adv1_title": "انغماس تام"'),
    ('"adv1_desc": "يعود طفلك كل مساء. يحافظ على رابط يومي متين مع أسرته."',
     '"adv1_desc": "رعاية إسلامية 24 ساعة: قرآن وأكاديمي ووجبات ورياضة ونوم في بيئة منظَّمة."'),
    ('"adv2_desc": "قرآن جادّ + أكاديمي متين، دون فراق الداخلية."',
     '"adv2_desc": "قرآن جادّ + أكاديمي متين، مع انضباط وصرامة الداخلية."'),
    ('"adv4_desc": "أقل تكلفةً من الداخلية إذ لا إقامة ولا وجبات."',
     '"adv4_desc": "الإقامة وثلاث وجبات حلال يوميًا مشمولة في الرسوم الشهرية."'),
    ('"adv6_desc": "يحقّق طلابنا الخارجيون نتائج ممتازة في التحفيظ والأكاديمي."',
     '"adv6_desc": "يحقّق طلابنا في البرنامج المختلط نتائج ممتازة في التحفيظ والأكاديمي."'),
    ('"cta_title": "سجّل طفلك في البرنامج المختلط"',
     '"cta_title": "سجّل طفلك في البرنامج المختلط الداخلي"'),
    ('"mixed": "برنامج مختلط (خارجي)"', '"mixed": "برنامج مختلط (داخلي)"'),
    # ── ES ──
    ('"mixed_subtitle": "Externado — vuelta a casa cada noche"',
     '"mixed_subtitle": "Internado — Corán y académico, alojamiento incluido"'),
    ('"card3_subtitle": "Externado: Corán por la mañana, académico por la tarde, vuelta a casa cada noche"',
     '"card3_subtitle": "Internado: Corán por la mañana, académico por la tarde, alojamiento incluido"'),
    ('"hero_title": "Programa Mixto en externado"', '"hero_title": "Programa Mixto Internado"'),
    ('"hero_subtitle": "Corán por la mañana, currículo académico por la tarde. Su hijo regresa a casa cada noche — para las familias que quieren mantener cerca a sus hijos mientras les ofrecen Tahfiz + estudios."',
     '"hero_subtitle": "Corán por la mañana, currículo académico por la tarde. Alojamiento y comidas incluidos — para las familias que desean ofrecer a sus hijos Tahfiz + estudios en un entorno islámico completo."'),
    ('"hero_badge": "Externado"', '"hero_badge": "Internado"'),
    ('"price_label3": "Vuelta a casa cada noche"', '"price_label3": "Alojamiento incluido"'),
    ('"features_intro": "La solución ideal para familias que desean combinar educación coránica y académica sin internado."',
     '"features_intro": "La solución ideal para familias que desean combinar educación coránica y académica en régimen de internado completo."'),
    ('"feat3_title": "Vuelta cada noche"', '"feat3_title": "Alojamiento incluido"'),
    ('"feat3_desc": "Su hijo regresa a casa cada noche. Ideal para las familias que desean mantenerse cerca."',
     '"feat3_desc": "Alojamiento y comidas incluidos. Su hijo está supervisado 24h en un entorno islámico acogedor."'),
    ('"sched_row_9": "Vuelta a casa"', '"sched_row_9": "Magrib y hora de dormir"'),
    ('"advantages_title": "¿Por qué elegir el externado?"', '"advantages_title": "¿Por qué elegir el programa mixto internado?"'),
    ('"adv1_title": "Vínculo familiar preservado"', '"adv1_title": "Inmersión total"'),
    ('"adv1_desc": "Su hijo regresa cada noche. Mantiene un vínculo diario fuerte con su familia."',
     '"adv1_desc": "Supervisión islámica 24h: Corán, académico, comidas, deporte y sueño en un entorno estructurado."'),
    ('"adv2_desc": "Corán serio + académico sólido, sin la separación del internado."',
     '"adv2_desc": "Corán serio + académico sólido, con la disciplina y el rigor del internado."'),
    ('"adv4_desc": "Menos costoso que el internado, ya que no incluye alojamiento ni comidas."',
     '"adv4_desc": "Alojamiento y 3 comidas halal diarias incluidos en la cuota mensual."'),
    ('"adv6_desc": "Nuestros alumnos de externado obtienen excelentes resultados en Tahfiz y académico."',
     '"adv6_desc": "Nuestros alumnos del programa mixto obtienen excelentes resultados en Tahfiz y académico."'),
    ('"cta_title": "Inscriba a su hijo en el Programa Mixto"',
     '"cta_title": "Inscriba a su hijo en el Programa Mixto Internado"'),
]

changed = 0
for old, new in replacements:
    if old in c:
        c = c.replace(old, new)
        changed += 1
    else:
        print(f"NOT FOUND: {old[:80]}")

with open(path, 'w', encoding='utf-8') as f:
    f.write(c)

print(f"translations.js: {orig_len} -> {len(c)} chars, {changed}/{len(replacements)} replacements applied")
