
import { Language, Category } from './types';

export const COLORS = {
  primary: '#2E86DE', // Vibrant Blue
  secondary: '#FF6B6B', // Soft Coral
  darkBlue: '#192A56', // Deep Navy Blue
  dark: '#2D3436', // Slate Grey
  light: '#F8F9FA', // Off-white
  white: '#FFFFFF',
  danger: '#FF4757',
  success: '#2ED573',
  warning: '#FFA502'
};

export const APP_NAME = "Meejo Manage";
export const CURRENCY = "FCFA";

export const formatCurrency = (amount: number): string => {
  return new Intl.NumberFormat('fr-FR').format(amount) + ' ' + CURRENCY;
};

export const generateReceiptNumber = (lastNumber: number): string => {
  const next = lastNumber + 1;
  return next.toString().padStart(6, '0');
};

export const playBeep = () => {
  const ctx = new (window.AudioContext || (window as any).webkitAudioContext)();
  const osc = ctx.createOscillator();
  const gain = ctx.createGain();
  osc.connect(gain);
  gain.connect(ctx.destination);
  osc.type = 'sine';
  osc.frequency.value = 880;
  gain.gain.value = 0.1;
  osc.start();
  setTimeout(() => osc.stop(), 100);
};

export const SYSTEM_CATEGORIES: Category[] = [
    { id: 'cat_couture', name: 'Couture', icon: 'Scissors', isSystem: true },
    { id: 'cat_fashion', name: 'Mode', icon: 'Shirt', isSystem: true },
    { id: 'cat_home', name: 'Maison', icon: 'Home', isSystem: true },
    { id: 'cat_electronics', name: 'Électronique', icon: 'Zap', isSystem: true },
    { id: 'cat_beauty', name: 'Beauté', icon: 'Heart', isSystem: true },
    { id: 'cat_kids', name: 'Enfant', icon: 'Smile', isSystem: true },
    { id: 'cat_sports', name: 'Sports', icon: 'Activity', isSystem: true },
    { id: 'cat_auto', name: 'Auto', icon: 'Truck', isSystem: true },
];

export const PACK_FEATURES = {
    STARTER: { web: true, sourcing: false, multiUser: false, crm: false, ai: false, voice: false, hr: false, productsLimit: 100 },
    PRO: { web: true, sourcing: true, multiUser: true, crm: true, ai: false, voice: false, hr: false, productsLimit: 500 },
    PREMIUM: { web: true, sourcing: true, multiUser: true, crm: true, ai: true, voice: true, hr: true, productsLimit: 99999 },
};

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  fr: {
    dashboard: 'Tableau de bord',
    pos: 'Caisse (POS)',
    products: 'Produits & Stock',
    promotions: 'Promotions',
    expenses: 'Dépenses',
    history: 'Historique',
    settings: 'Paramètres',
    logout: 'Déconnexion',
    shareholder: 'Actionnaires',
    sourcing: 'Sourcing & Alibaba',
    hr: 'Ressources Humaines',
    webstore: 'Site Vitrine',
    crm: 'CRM & Clients',
    marketplace: 'Mall Digital',
    login_title: 'Connexion Meejo',
    login_subtitle: 'Authentification Sécurisée',
    email_placeholder: 'Email',
    password_placeholder: 'Mot de passe',
    login_button: 'Se connecter',
    mfa_title: 'Authentification Google',
    mfa_subtitle: 'Scannez le QR Code ou entrez le code à 6 chiffres de votre application Google Authenticator',
    verify_button: 'Valider le code',
    revenue_today: "CA Aujourd'hui",
    revenue_month: "CA Ce Mois",
    total_products: "Total Produits",
    low_stock: "Alerte Stock",
    top_products: "Top Ventes",
    sales_chart: "Évolution des Ventes",
    channel_stats: "Sources de Vente",
    add_product: "Nouveau Produit",
    search_placeholder: "Rechercher...",
    catalog: "Catalogue",
    cart: "Panier",
    checkout: "ENCAISSER",
    total: "Total",
    pay_modal_title: "Paiement",
    pay_date: "Date de règlement",
    pay_method: "Mode de paiement",
    sales_channel: "Source",
    amount_received: "Montant Reçu",
    change_due: "Monnaie à rendre",
    remaining_due: "Reste à payer",
    validate: "VALIDER",
    cancel: "Annuler",
    customer_contact: "Contact Client",
    customer_email: "Email Client",
    expense_new: "Nouvelle Dépense",
    expense_date: "Date",
    expense_cat: "Catégorie",
    expense_desc: "Description",
    expense_amount: "Montant",
    shareholder_dashboard: "Espace Actionnaire",
    net_profit: "Bénéfice Net",
    my_shares: "Mes Parts",
    my_dividends: "Mes Dividendes (Estimés)",
    actions: "Actions",
    image: "Image",
    stock: "Stock",
    price: "Price",
    shipments: "Commandes Alibaba / Cargo",
    cbm_calculator: "Calculateur Auto CBM/Poids",
    employees: "Employés",
    salaries: "Salaires",
    import_data: "Importer Données",
    home: "Accueil",
    shop: "Boutique",
    about: "À Propos",
    contact: "Contact",
    my_cart: "Mon Panier",
    add_to_cart: "Ajouter au panier",
    buy_now: "Acheter",
    payment_secure: "Paiement Sécurisé",
    scan_to_pay: "Scannez pour payer",
    click_to_pay: "Cliquez pour payer"
  },
  en: {
    dashboard: 'Dashboard',
    pos: 'Point of Sale',
    products: 'Products & Stock',
    promotions: 'Promotions',
    expenses: 'Expenses',
    history: 'History',
    settings: 'Settings',
    logout: 'Logout',
    shareholder: 'Shareholders',
    sourcing: 'Sourcing & Alibaba',
    hr: 'Human Resources',
    webstore: 'Web Store',
    crm: 'CRM & Customers',
    marketplace: 'Digital Mall',
    login_title: 'Meejo Login',
    login_subtitle: 'Secure Authentication',
    email_placeholder: 'Email',
    password_placeholder: 'Password',
    login_button: 'Login',
    mfa_title: 'Google Authentication',
    mfa_subtitle: 'Scan QR Code or enter the 6-digit code from your Google Authenticator app',
    verify_button: 'Verify Code',
    revenue_today: "Revenue Today",
    revenue_month: "Revenue This Month",
    total_products: "Total Products",
    low_stock: "Low Stock Alert",
    top_products: "Top Selling",
    sales_chart: "Sales Evolution",
    channel_stats: "Sales Sources",
    add_product: "New Product",
    search_placeholder: "Search...",
    catalog: "Catalog",
    cart: "Cart",
    checkout: "CHECKOUT",
    total: "Total",
    pay_modal_title: "Payment",
    pay_date: "Payment Date",
    pay_method: "Payment Method",
    sales_channel: "Source",
    amount_received: "Amount Received",
    change_due: "Change Due",
    remaining_due: "Remaining Due",
    validate: "CONFIRM",
    cancel: "Cancel",
    customer_contact: "Customer Contact",
    expense_new: "New Expense",
    expense_date: "Date",
    expense_cat: "Category",
    expense_desc: "Description",
    expense_amount: "Amount",
    shareholder_dashboard: "Shareholder Space",
    net_profit: "Net Profit",
    my_shares: "My Shares",
    my_dividends: "My Dividends (Est.)",
    actions: "Actions",
    image: "Image",
    stock: "Stock",
    price: "Price",
    shipments: "Alibaba / Cargo Orders",
    cbm_calculator: "Auto CBM/Weight Calculator",
    employees: "Employees",
    salaries: "Salaries",
    import_data: "Import Data",
    home: "Home",
    shop: "Shop",
    about: "About",
    contact: "Contact",
    my_cart: "My Cart",
    add_to_cart: "Add to cart",
    buy_now: "Buy Now",
    payment_secure: "Secure Payment",
    scan_to_pay: "Scan to pay",
    click_to_pay: "Click to pay"
  },
  ar: {
    dashboard: 'لوحة القيادة',
    pos: 'نقطة البيع',
    products: 'المنتجات والمخزون',
    promotions: 'العروض',
    expenses: 'المصاريف',
    history: 'السجل',
    settings: 'الإعدادات',
    logout: 'تسجيل خروج',
    shareholder: 'المساهمين',
    sourcing: 'الاستيراد والشحن',
    hr: 'الموارد البشرية',
    webstore: 'المتجر الإلكتروني',
    crm: 'إدارة العملاء',
    marketplace: 'السوق الرقمi',
    login_title: 'تسجيل دخول ميجو',
    login_subtitle: 'مصادقة آمنة',
    email_placeholder: 'البريد الإلكتروني',
    password_placeholder: 'كلمة المرور',
    login_button: 'دخول',
    mfa_title: 'مصادقة جوجل',
    mfa_subtitle: 'امسح رمز QR أو أدخل الرمز المكون de 6 أرقام de تطبيق Google Authenticator',
    verify_button: 'تحقق',
    revenue_today: "إيرادات اليوم",
    revenue_month: "إيرادات الشهر",
    total_products: "إجمالي المنتجات",
    low_stock: "تنبيه المخزون",
    top_products: "الأكثر مبيعاً",
    sales_chart: "تطور المبيعات",
    channel_stats: "مصادر البيع",
    add_product: "منتج جديد",
    search_placeholder: "بحث...",
    catalog: "الكتالوج",
    cart: "السلة",
    checkout: "دفع",
    total: "المجموع",
    pay_modal_title: "دفع",
    pay_date: "تاريخ الدفع",
    pay_method: "طريقة الدفع",
    sales_channel: "المصدر",
    amount_received: "المبلغ المستلم",
    change_due: "الباقي",
    remaining_due: "المبلغ المتبقي",
    validate: "تأكيد",
    cancel: "إلغاء",
    customer_contact: "رقم العميل",
    expense_new: "مصروف جديد",
    expense_date: "تاريخ",
    expense_cat: "فئة",
    expense_desc: "وصف",
    expense_amount: "مبلغ",
    shareholder_dashboard: "فضاء المساهمين",
    net_profit: "الربح الصافي",
    my_shares: "حصتي",
    my_dividends: "أرباحي (تقديري)",
    actions: "إجراءات",
    image: "صورة",
    stock: "مخزون",
    price: "سعر",
    shipments: "الشحنات",
    cbm_calculator: "حاسبة الوزن/الحجم",
    employees: "الموظفين",
    salaries: "الرواتب",
    import_data: "استيراد البيانات",
    home: "الرئيسية",
    shop: "المتجر",
    about: "من نحن",
    contact: "اتصل بنا",
    my_cart: "سلتي",
    add_to_cart: "أضف للسلة",
    buy_now: "اشتر الآن",
    payment_secure: "دفع آمن",
    scan_to_pay: "امسح للدفع",
    click_to_pay: "انقر للدفع"
  }
};

export const t = (key: string, lang: Language): string => {
  return TRANSLATIONS[lang][key] || key;
};
